[build]
builder = "dockerfile"
dotnet-version = "9.0"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "dotnet KOAHome.dll"
restartPolicyType = "Always"
healthcheckPath = "/health"

[service]
port = 5000
