name: Nightly Shutdown

on:
  schedule:
    - cron: '0 9 * * *' # 16h giờ Việt Nam (Railway giờ UTC)
    - cron: '0 10 * * *'  # 17h sáng giờ Việt Nam (Railway giờ UTC)
  workflow_dispatch: # Cho phép chạy tay

jobs:
  stop:
    if: github.event.schedule == '0 9 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Stop Project
        run: railway down --project <project-name-or-id>
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  start:
    if: github.event.schedule == '0 10 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g railway
      - name: Start Project
        run: railway up --project <project-name-or-id>
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
