name: Sync Google Sheet

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X POST \
          https://koa-home-manager.up.railway.app/Dashboards/SyncGoogleSheet \
          -H "Content-Type: application/json"
